LDFLAGS += -lavformat -lavcodec -lswscale -lavutil -lavfilter -lswresample -lavdevice -lz -llzma -lbz2 -lrt -ljpeg -lpthread
#-lpostproc -lao -lva -lx264
CFLAGS += -D_GNU_SOURCE

-include ../Examples.mk
