#!/bin/sh
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ERROR=false
if [ -z $1 ]; then
	ERROR=true
elif [ $1 != "start" ]; then
	if [ $1 != "stop" ]; then
		ERROR=true
	fi
fi
if [ $ERROR = true ]; then
	echo "ERROR: Use start/stop to start or stop ActiveMQ broker"

elif [ -e $SCRIPT_DIR/../gaps.ma.dependencies/deps/activemq/activemq/bin/activemq ]
then
	echo "Starting ActiveMQ Broker..."
	$SCRIPT_DIR/../gaps.ma.dependencies/deps/activemq/activemq/bin/activemq $1
else
	echo "ActiveMQ Service Broker is not installed properly. Run install-activemq.sh first."
fi
