/* Entire file to be autogenerated by CAPO */

#ifndef _PURPLE_RPC_
#define _PURPLE_RPC_
#include "xdcomms.h"
#include "codec.h"

# define MUX_NEXTRPC    1
# define SEC_NEXTRPC    1
# define MUX_OKAY       2
# define SEC_OKAY       2
# define MUX_REQUESTA   1
# define SEC_REQUESTA   1
# define MUX_RESPONSEA  2
# define SEC_RESPONSEA  2

extern void   _hal_init(char *inuri, char *outuri);
extern void   _notify_next_tag(gaps_tag* n_tag);
extern double _rpc_get_a();

#endif /* _PURPLE_RPC_ */

