name: learn-github-actions
run-name: ${{ github.actor }} is learning github actions
on: [push]

jobs:
  check-pytest-version:
    runs-on: ubuntu-latest
    steps:      
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
        
      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
      - name: install pytest
        run: pip install -U pytest
      - run: pytest --version
        
      - name: test docker pull
        run: docker pull gapsclosure/closuredev:develop
      - name: test git clone
        run: git clone --recurse-submodules https://github.com/gaps-closure/build.git
      - name: test container up
        run: devcontainer up --config build/apps/examples/example1/.cicd/devcontainer.json --workspace-folder build/apps/examples example1
